### ISSUE TITLE
Faye example works, but socket.io example fails

### ISSUE THREAD

**Issue by fracturedexistence** [tjanczuk/dante#7]
I followed the instructions for hosting in IIS 8.0, 

https://mysite/dante/server-faye.js 
works fine

https://mysite/dante/server-socketio.js 
fails with the following error

iisnode encountered an error when processing the request.
HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1002
HTTP reason: Internal Server Error

You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.The last 64k of the output generated by the node.exe process to stderr is shown below:

Application has thrown an uncaught exception and is terminated:
TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (D:\webapps\mysite\websocketsvr\node_modules\socket.io\lib\store.js:35:42)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\webapps\mysite\websocketsvr\node_modules\socket.io\lib\manager.js:16:13)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)

**My setup...**
Windows Server 2012/R2, IIS 8.5
Node.js (v13.12.0)
NPM (v6.14.4)
URL Rewrite (v2.1 - installed from package manager)
IISNode (iisnode-full-v0.2.21-x64.msi - obtained from https://github.com/azure/iisnode/wiki/iisnode-releases)

**npm list**
dante@0.0.2 D:\webapps\mysite\websocketsvr

+-- faye-websocket@0.4.3
`-- socket.io@0.9.13
  +-- base64id@0.1.0
  +-- policyfile@0.0.4
  +-- redis@0.7.3
  `-- socket.io-client@0.9.11
    +-- active-x-obfuscator@0.0.1
    | `-- zeparser@0.0.5
    +-- uglify-js@1.2.5
    +-- ws@0.4.32
    | +-- commander@2.1.0
    | +-- nan@1.0.0
    | +-- options@0.0.6
    | `-- tinycolor@0.0.1
    `-- xmlhttprequest@1.4.2

**Comment by fracturedexistence** [comment]
Never mind. I solved this.
I had installed the wrong node server. 
I stupidly installed OpenJs node.js, instead of Microsoft's node.js
